[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # black-default
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.poetry]
name = "qustop"
version = "0.0.1"
description = "Python tools for the optimizing over quantum states."
authors = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
maintainers = [
    "Vincent Russo <vincentrusso1@gmail.com>"
]
readme = "README.md"
homepage = "https://vprusso.github.io/toqito/"
repository = "https://github.com/vprusso/toqito"
keywords = ["quantum information", "quantum computing", "quantum state optimization", "quantum state distinguishability"]


[tool.poetry.dependencies]
python = "^3.7"
cvx = "*"
cvxpy = "*"
numpy = "*"
scipy = "*"
toqito = "*"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-docstrings = "^1.5"
ipython = "*"
pep8 = "^1.7"
pylint = "^2.4"
pytest = "*"
pytest-cov = "*"
mypy = "^0.750.0"
coverage = "^4.5"
coveralls = "^1.9"
recommonmark = "*"
sphinx = "*"
sphinx_rtd_theme = "*"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
